### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pavankvch** [hamidness/restring#16]
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at com.ice.restring.SharedPrefStringRepository.deserializeKeyValues(SharedPrefStringRepository.java:83)
        at com.ice.restring.SharedPrefStringRepository.loadStrings(SharedPrefStringRepository.java:65)
        at com.ice.restring.SharedPrefStringRepository.<init>(SharedPrefStringRepository.java:23)
        at com.ice.restring.Restring.initStringRepository(Restring.java:81)
        at com.ice.restring.Restring.init(Restring.java:40)``

**Comment by iTruff** [comment]
Same :(

**Comment by iTruff** [comment]
@pavankvch 

Bug with serializing your strings in SharedPreferences. To avoid it, you can disable saving strings in SharedPreferences by setting up Restring like this:

Restring.init(context,
              new RestringConfig.Builder()
                  .persist(false) // Set this to false to prevent saving into shared preferences.
                  .build()
        );

Now it will works fine.
For using SharedPreferences look at #13 pull request.
