### ISSUE TITLE
[API 19] java.lang.NoClassDefFoundError: android.widget.Toolbar

### ISSUE THREAD

**Issue by Aleksander3007** [hamidness/restring#25]
On devices API 19:
```
java.lang.NoClassDefFoundError: android.widget.Toolbar
        at com.ice.restring.ToolbarTransformer.getViewType(ToolbarTransformer.java:21)
        at com.ice.restring.ViewTransformerManager.registerTransformer(ViewTransformerManager.java:24)
        at com.ice.restring.Restring.initViewTransformer(Restring.java:94)
        at com.ice.restring.Restring.init(Restring.java:41)
```

**Comment by dbotelho** [comment]
Is this project active? https://github.com/hamidness/restring/pull/22 fixes this. Why it's not merged yet??

**Comment by dbotelho** [comment]
Hotfix for those that have production apps using this library:
`    implementation 'com.github.amilcar-sr:restring:2d6ea5f3030c5fcc725dd918e72e0923e148c5ea'`
